import Head from 'next/head';
const { DateTime } = require('luxon');
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';
import axios from 'axios';

export default function Home() {
  const [checkins, setCheckins] = useState([]);
  useEffect(() => {
    axios.get('http://localhost:3000/api/checkin').then((res) => {
      setCheckins(res?.data?.data || []);
    });
    // console.log(DateTime.fromFormat('2022-07-27T02:14:58.658Z').toLocal());
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {checkins.map((c, idx) => {
          return (
            <div key={idx}>
              <p>
                {c.created_at} - {c.timezone}
              </p>
              <p>{DateTime.fromISO(c.created_at).setZone(c.timezone).toString()}</p>
            </div>
          );
        })}
      </main>

      <footer className={styles.footer}>
        <a href="https://app.cyclic.sh" target="_blank" rel="noopener noreferrer">
          Powered by <span className={styles.logo}>Cyclic</span>
        </a>
      </footer>
    </div>
  );
}
